server:
  port: 8081
  servlet:
    context-path: /api

spring:
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/bank}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

backend:
  diary-limit: 1000